[pytest]
testpaths = tests
python_files = test_*.py
norecursedirs = scratch .venv .git migrations
filterwarnings =
    ignore::DeprecationWarning
    ignore::sqlalchemy.exc.SAWarning
    ignore::sqlalchemy.exc.LegacyAPIWarning
