"""add prescription_base64 to sales_bills

Revision ID: 084cd999da74
Revises: d580376bcbea
Create Date: 2026-04-29 16:42:41.998924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '084cd999da74'
down_revision = 'd580376bcbea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prescription_base64', sa.Text(), nullable=True))

    with op.batch_alter_table('wanted_list', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'selenium_order_logs', ['selenium_log_id'], ['selenium_log_id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wanted_list', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('sales_bills', schema=None) as batch_op:
        batch_op.drop_column('prescription_base64')

    # ### end Alembic commands ###
