"""fix ai_face_log autoincrement

Revision ID: 0ede8838df32
Revises: 937df8029ff5
Create Date: 2026-05-10 23:26:35.051828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '0ede8838df32'
down_revision = '937df8029ff5'
branch_labels = None
depends_on = None


def _is_already_uuid(table, column):
    """Return True if the column is already UUID type (not NUMERIC/INTEGER)."""
    bind = op.get_bind()
    insp = inspect(bind)
    cols = {c['name']: str(c['type']).upper() for c in insp.get_columns(table)}
    col_type = cols.get(column, '')
    return 'UUID' in col_type or 'CHAR' in col_type  # UUID shows as UUID or CHAR(32)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Guard: on a fresh DB built from init_db, all FK columns are already UUID.
    # This migration was generated to fix a legacy DB with NUMERIC-typed columns.
    # Skip all alterations if users.user_id is already UUID.
    if _is_already_uuid('users', 'user_id'):
        return

    with op.batch_alter_table('approval_logs', schema=None) as batch_op:
        batch_op.alter_column('requested_by',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('approved_by',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('prescription_ocr_logs', schema=None) as batch_op:
        batch_op.alter_column('verified_by',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=True)

    with op.batch_alter_table('purchase_invoices', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('purchase_payments', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('purchase_returns', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('receipts_payments', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('sales_bills', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('cancelled_by',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('sales_returns', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('sales_returns', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('sales_bills', schema=None) as batch_op:
        batch_op.alter_column('cancelled_by',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('receipts_payments', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('purchase_returns', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('purchase_payments', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('purchase_invoices', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('prescription_ocr_logs', schema=None) as batch_op:
        batch_op.alter_column('verified_by',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('approval_logs', schema=None) as batch_op:
        batch_op.alter_column('approved_by',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('requested_by',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    op.create_table('_alembic_tmp_ai_face_logs',
    sa.Column('log_id', sa.BIGINT(), nullable=False),
    sa.Column('camera_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('detected_at', sa.DATETIME(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.Column('confidence_score', sa.FLOAT(), nullable=True),
    sa.Column('action_triggered', sa.VARCHAR(length=100), nullable=True),
    sa.Column('is_fraud_alert', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    # ### end Alembic commands ###
