"""add reorder_requests table with n8n conversation fields

Revision ID: 15744d132e82
Revises: f8a86ab9cfa2
Create Date: 2026-05-27 12:37:25.056893

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '15744d132e82'
down_revision = 'f8a86ab9cfa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reorder_requests',
    sa.Column('reorder_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('n8n_conversation_id', sa.String(length=100), nullable=True),
    sa.Column('supplier_response', sa.Text(), nullable=True),
    sa.Column('confirmed_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provider_message_id', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('PENDING', 'PROCESSING', 'SENT', 'PARTIALLY_CONFIRMED', 'CONFIRMED', 'FAILED', 'REJECTED')", name='reorder_status_valid'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('reorder_id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('face_embedding',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('face_embedding',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    op.drop_table('reorder_requests')
    # ### end Alembic commands ###
