"""add loyalty tracking and chronic flag

Revision ID: 9fbb3e6b6d8b
Revises: cd394e1824f8
Create Date: 2026-05-15 20:51:40.158271

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9fbb3e6b6d8b'
down_revision = 'cd394e1824f8'
branch_labels = None
depends_on = None


from sqlalchemy import inspect

def _column_exists(table, column):
    bind = op.get_bind()
    insp = inspect(bind)
    cols = [c['name'] for c in insp.get_columns(table)]
    return column in cols

def _table_exists(table):
    bind = op.get_bind()
    insp = inspect(bind)
    return table in insp.get_table_names()

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if _table_exists('sms_log'):
        op.drop_table('sms_log')
    
    with op.batch_alter_table('customers', schema=None) as batch_op:
        if not _column_exists('customers', 'total_spend'):
            batch_op.add_column(sa.Column('total_spend', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0.00'))
        if not _column_exists('customers', 'total_visits'):
            batch_op.add_column(sa.Column('total_visits', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('customer_purchase_patterns', schema=None) as batch_op:
        if not _column_exists('customer_purchase_patterns', 'is_chronic'):
            batch_op.add_column(sa.Column('is_chronic', sa.Boolean(), nullable=False, server_default='false'))

    with op.batch_alter_table('sales_bills', schema=None) as batch_op:
        if not _column_exists('sales_bills', 'payment_mode'):
            batch_op.add_column(sa.Column('payment_mode', sa.String(length=20), nullable=False, server_default='cash'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_bills', schema=None) as batch_op:
        batch_op.drop_column('payment_mode')

    with op.batch_alter_table('customer_purchase_patterns', schema=None) as batch_op:
        batch_op.drop_column('is_chronic')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('total_visits')
        batch_op.drop_column('total_spend')

    op.create_table('sms_log',
    sa.Column('sms_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('recipient_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('ref_type', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('ref_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.CheckConstraint("status::text = ANY (ARRAY['SENT'::character varying, 'PENDING'::character varying, 'FAILED'::character varying]::text[])", name=op.f('sms_status_check')),
    sa.PrimaryKeyConstraint('sms_id', name=op.f('sms_log_pkey'))
    )
    # ### end Alembic commands ###
