"""fix_missing_wanted_list_reason_and_user_fields

Revision ID: c497879eb940
Revises: 43bdada2911f
Create Date: 2026-05-15 15:49:41.900324

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c497879eb940'
down_revision = '43bdada2911f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_face_logs', schema=None) as batch_op:
        batch_op.alter_column('confidence_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_column('face_snapshot_url')

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.alter_column('old_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('new_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('prescription_ocr_logs', schema=None) as batch_op:
        batch_op.alter_column('raw_extracted_text',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('parsed_medicines',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.alter_column('b2b_credentials',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('wanted_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_face_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('face_snapshot_url', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('confidence_score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.alter_column('new_value',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('old_value',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('prescription_ocr_logs', schema=None) as batch_op:
        batch_op.alter_column('parsed_medicines',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('raw_extracted_text',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.alter_column('b2b_credentials',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('wanted_list', schema=None) as batch_op:
        batch_op.drop_column('reason')

    # ### end Alembic commands ###
