"""add stock adjustment table

Revision ID: cd394e1824f8
Revises: d966ac1cd6fe
Create Date: 2026-05-13 23:08:51.113648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd394e1824f8'
down_revision = 'd966ac1cd6fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_adjustments',
    sa.Column('adjustment_id', sa.BigInteger(), nullable=False),
    sa.Column('stock_batch_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=10), nullable=False),
    sa.Column('adj_date', sa.Date(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['stock_batch_id'], ['stock_batches.stock_batch_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('adjustment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_adjustments')
    # ### end Alembic commands ###
